/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import Cliente.Cliente;
import Produto.Produto;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.util.Date;
import javax.imageio.ImageIO;

/**
 *
 * @author victor.rslucca
 */
public class inicial extends javax.swing.JFrame {
    
    TelaVendas realizaVenda = null;
    TelaCliente clienteSel = null;
    Relatorio1 relat = null;
    TelaProduto telaProdutos = null;    
    
    /**
     * Creates new form inicial
     */
    public inicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VendaButton = new javax.swing.JButton();
        ProdutoButton = new javax.swing.JButton();
        ClienteButton = new javax.swing.JButton();
        RelatorioButton = new javax.swing.JButton();
        NomeLojaLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(167, 355));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        VendaButton.setText("VENDA");
        VendaButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        VendaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendaButtonActionPerformed(evt);
            }
        });

        ProdutoButton.setText("PRODUTO");
        ProdutoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ProdutoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutoButtonActionPerformed(evt);
            }
        });

        ClienteButton.setText("CLIENTE");
        ClienteButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteButtonActionPerformed(evt);
            }
        });

        RelatorioButton.setText("RELATORIO");
        RelatorioButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RelatorioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatorioButtonActionPerformed(evt);
            }
        });

        NomeLojaLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        NomeLojaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomeLojaLabel.setText("Moda Fashion");
        NomeLojaLabel.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClienteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProdutoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VendaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RelatorioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(NomeLojaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ClienteButton, ProdutoButton, RelatorioButton, VendaButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NomeLojaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VendaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProdutoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClienteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RelatorioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ClienteButton, ProdutoButton, RelatorioButton, VendaButton});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteButtonActionPerformed
        // TODO add your handling code here:
        if (clienteSel == null || !clienteSel.isDisplayable()) {
            clienteSel = new TelaCliente();
            clienteSel.setVisible(true);
            //this.dispose();
        }
        /*
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        */
        clienteSel.toFront();
    }//GEN-LAST:event_ClienteButtonActionPerformed

    private void VendaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendaButtonActionPerformed
        // TODO add your handling code here:
        if (realizaVenda == null || !realizaVenda.isDisplayable()) {
            realizaVenda = new TelaVendas();
            realizaVenda.setLocationRelativeTo(null);
            realizaVenda.setVisible(true);
            //this.dispose();
        }
        /*
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        */
        realizaVenda.toFront();
    }//GEN-LAST:event_VendaButtonActionPerformed

    private void ProdutoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutoButtonActionPerformed
        if (telaProdutos == null || !telaProdutos.isDisplayable()) {
            telaProdutos = new TelaProduto();
            telaProdutos.setVisible(true);
        }
        telaProdutos.toFront();
    }//GEN-LAST:event_ProdutoButtonActionPerformed
    
    private void RelatorioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatorioButtonActionPerformed
        if (relat == null || !relat.isDisplayable()) {
            relat = new Relatorio1();
            relat.setVisible(true);
            //this.dispose();
        }
        relat.toFront();
    }//GEN-LAST:event_RelatorioButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    }//GEN-LAST:event_formWindowOpened
    /*public void liberar(){
        
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        
    }
    */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*
        Produto produto = new Produto();
        produto.setColecao("Outono");
        produto.setCor("Azul");
        produto.setNome("Calça");
        produto.setPreco(50);
        produto.setQuantidade(100);
        produto.setSexo("Homem");
        produto.setTamanho("M");
        Mock.mockProduto.inserir(produto);
        
        Produto produto1 = new Produto();
        produto1.setColecao("Primaveira");
        produto1.setCor("Amarelo");
        produto1.setNome("Blusa");
        produto1.setPreco(25);
        produto1.setQuantidade(200);
        produto1.setSexo("Mulher");
        produto1.setTamanho("G");
        
        Mock.mockProduto.inserir(produto1);

        Cliente cli = new Cliente();
        cli.setBairro("Vila Campo Grande");
        cli.setCPFCNPJ("18131157881");
        cli.setCep("04455310");
        cli.setCidade("São Paulo");
        cli.setComplemento("APTO");
        Date data = new Date();
        cli.setDataNascimento(data);
        cli.setEmail("victor.rafalucca@gmail.com");
        cli.setEstado("SP");
        cli.setEndereco("Rua Engenheio Domicio de L Pacheo e silva");
        cli.setNome("Victor");
        cli.setNumEnd("586");
        cli.setSobrenome("de Lucca");
        cli.setTelefone("11953933450");
        
        Mock.mockCliente.inserir(cli);*/
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClienteButton;
    private javax.swing.JLabel NomeLojaLabel;
    private javax.swing.JButton ProdutoButton;
    private javax.swing.JButton RelatorioButton;
    private javax.swing.JButton VendaButton;
    // End of variables declaration//GEN-END:variables
}
