package tela;

import Cliente.Cliente;
import Exception.DataSourceException;
import Exception.VendaException;
import Produto.Produto;
import Servico.ServicoProduto;
import Servico.ServicoVenda;
import Venda.ItensVenda;
import Venda.Venda;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.xml.bind.ParseConversionEvent;

public class TelaVendas extends javax.swing.JFrame {

    /* Criado três parametros globais: ItensVenda para o carrinho, Cliente para o cliente
    e date x para a data
     */
    private ArrayList<ItensVenda> itensVendas = new ArrayList<>();
    private Cliente clientes = new Cliente();
    double precoT = 0;
    Date x = new Date();

    /**
     * Creates new form TelaVendas
     */
    public TelaVendas() {
        initComponents();
        this.setLocationRelativeTo(null);
        SimpleDateFormat formater = new SimpleDateFormat("dd/MM/yyyy");
        data.setText(formater.format(x));
        cpfText.setEditable(false);
        nomeText.setEditable(false);
        data.setEditable(false);
        totalVendaText.setEditable(false);
        DefaultTableModel tabela = (DefaultTableModel) ProdTable.getModel();
        tabela.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formaPagamentoButton = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        buscarClienteButton = new javax.swing.JButton();
        buscarProdButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ProdTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        finalizarVendaButton = new javax.swing.JButton();
        cancelarVendaButton = new javax.swing.JButton();
        nomeText = new javax.swing.JTextField();
        cpfText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        totalVendaText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        data = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Vendas");

        buscarClienteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/magnifier.png"))); // NOI18N
        buscarClienteButton.setText("Buscar Cliente");
        buscarClienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarClienteButtonActionPerformed(evt);
            }
        });

        buscarProdButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/book_add.png"))); // NOI18N
        buscarProdButton.setText("Adicionar Produto");
        buscarProdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarProdButtonActionPerformed(evt);
            }
        });

        ProdTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Tamanho", "Cor", "Coleção", "Preço", "Qtd Estoque", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProdTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(ProdTable);

        jLabel2.setText("Nome");

        jLabel3.setText("CPF");

        jLabel4.setText("Forma de pagamento");

        finalizarVendaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/tick.png"))); // NOI18N
        finalizarVendaButton.setText("Finalizar Compra");
        finalizarVendaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarVendaButtonActionPerformed(evt);
            }
        });

        cancelarVendaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancel.png"))); // NOI18N
        cancelarVendaButton.setText("Cancelar");
        cancelarVendaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarVendaButtonActionPerformed(evt);
            }
        });

        nomeText.setBackground(new java.awt.Color(204, 204, 204));
        nomeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextActionPerformed(evt);
            }
        });

        cpfText.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setText("Total");

        totalVendaText.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setText("Data");

        formaPagamentoButton.add(jRadioButton1);
        jRadioButton1.setText("Dinheiro");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        formaPagamentoButton.add(jRadioButton2);
        jRadioButton2.setText("Cartão de Credito/Debito");

        data.setBackground(new java.awt.Color(204, 204, 204));
        data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jButton1.setText("Remover Item");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 758, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cancelarVendaButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(finalizarVendaButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(totalVendaText, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jRadioButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(61, 61, 61)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(84, 84, 84))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(cpfText, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                                    .addComponent(nomeText))
                                                .addGap(13, 13, 13)))))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buscarProdButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buscarClienteButton)
                        .addGap(190, 190, 190))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(nomeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(cpfText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton2)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buscarClienteButton)
                            .addComponent(buscarProdButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(totalVendaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finalizarVendaButton)
                    .addComponent(cancelarVendaButton))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarProdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProdButtonActionPerformed
        buscaProduto dlg = new buscaProduto(this, true);
        ItensVenda itens = dlg.selecionarItemVenda();
        boolean prodI=true;
        if (!itensVendas.isEmpty()) {
            for (int i = 0; i < itensVendas.size(); i++) {
                if (itensVendas.get(i).getProduto().getID()==itens.getProduto().getID()) {
                    prodI=false;
                    break;
                }
            }
        }    
        if (itens != null && itens.getProduto() != null && itens.getQtdProduto() > 0 && prodI==true) {
            Object[] populaTab = new Object[7];
            DefaultTableModel tabela = (DefaultTableModel) ProdTable.getModel();
            populaTab[0] = itens.getProduto().getNome();
            populaTab[1] = itens.getProduto().getTamanho();
            populaTab[2] = itens.getProduto().getCor();
            populaTab[3] = itens.getProduto().getColecao();
            populaTab[4] = itens.getProduto().getPreco();
            populaTab[5] = itens.getProduto().getQuantidade();
            populaTab[6] = itens.getQtdProduto();
            tabela.addRow(populaTab);
            precoT += (itens.getProduto().getPreco()) * ((double)itens.getQtdProduto());
            itensVendas.add(itens);
            totalVendaText.setText(Double.toString(precoT));
        } else {
            JOptionPane.showMessageDialog(rootPane, "Nenhum Produto Selecionado ou produto já esta no carrinho");
        }
        //Finalizado
    }//GEN-LAST:event_buscarProdButtonActionPerformed

    private void buscarClienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarClienteButtonActionPerformed
        // Falta a tela de buscar o cliente e preencher os campos
        BuscarCliente dlg = new BuscarCliente(this, true);
        clientes = dlg.buscarCliVenda();
        nomeText.setText(clientes.getNome());
        cpfText.setText(clientes.getCPFCNPJ());
    }//GEN-LAST:event_buscarClienteButtonActionPerformed

    private void finalizarVendaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarVendaButtonActionPerformed
        
        SimpleDateFormat formater = new SimpleDateFormat("dd/MM/yyyy");
        Venda vend = new Venda();
        vend.setItens(itensVendas);
        vend.Cliente(clientes);
        if (jRadioButton1.isSelected()) {
            vend.setFormaPagamento(jRadioButton1.getText());
        }
        if (jRadioButton2.isSelected()) {
            vend.setFormaPagamento(jRadioButton2.getText());
        }
        vend.setDataVenda(x);
        vend.setTotalVenda();
        try {
            ServicoVenda.cadastrarVenda(vend);
        } catch (VendaException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            return;
        } catch (DataSourceException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            return;
        }
        JOptionPane.showMessageDialog(this, "Venda finalizada com sucesso");
        DefaultTableModel tabela = (DefaultTableModel) ProdTable.getModel();
        tabela.setRowCount(0);
        precoT=0;
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        totalVendaText.setText("");
        cpfText.setText("");
        nomeText.setText("");
        itensVendas = new ArrayList<ItensVenda>();
        clientes = new Cliente();
        //Finalizado
    }//GEN-LAST:event_finalizarVendaButtonActionPerformed

    private void cancelarVendaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarVendaButtonActionPerformed

        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarVendaButtonActionPerformed

    private void nomeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int linhaSelec = ProdTable.getSelectedRow();
        itensVendas.remove(linhaSelec);
        precoT-=(Double)ProdTable.getValueAt(linhaSelec, 4);
        DefaultTableModel tabela = (DefaultTableModel) ProdTable.getModel();
        tabela.removeRow(linhaSelec);  
        totalVendaText.setText(Double.toString(precoT));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ProdTable;
    private javax.swing.JButton buscarClienteButton;
    private javax.swing.JButton buscarProdButton;
    private javax.swing.JButton cancelarVendaButton;
    private javax.swing.JTextField cpfText;
    private javax.swing.JFormattedTextField data;
    private javax.swing.JButton finalizarVendaButton;
    private javax.swing.ButtonGroup formaPagamentoButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeText;
    private javax.swing.JTextField totalVendaText;
    // End of variables declaration//GEN-END:variables

}
